version: '3'
services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
  frontend:
    build: ../LearnHub
    ports:
      - "80:80"
    links:
      - mongodb
      - redis
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
  mongo-data: